default_twitter: &default_twitter
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>

development:
  <<: *default_twitter

test:
  <<: *default_twitter

production:
  <<: *default_twitter